# Copyright (C) 2011 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/samsung/galaxys_sc02b/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/samsung/galaxys_sc02b/proprietary/lib/hw/gps.s5pc110.so:system/lib/hw/gps.s5pc110.so \
    vendor/samsung/galaxys_sc02b/proprietary/lib/libemoji_docomo.so:system/lib/libemoji_docomo.so \
    vendor/samsung/galaxys_sc02b/proprietary/lib/libril.so:system/lib/libril.so \
    vendor/samsung/galaxys_sc02b/proprietary/lib/libsecril-client.so:system/lib/libsecril-client.so \
    vendor/samsung/galaxys_sc02b/proprietary/lib/libsec-ril.so:system/lib/libsec-ril.so \
    vendor/samsung/galaxys_sc02b/proprietary/lib/libsensor_yamaha_test.so:system/lib/libsensor_yamaha_test.so \
    vendor/samsung/galaxys_sc02b/proprietary/bin/geomagneticd:system/bin/geomagneticd \
    vendor/samsung/galaxys_sc02b/proprietary/bin/gpsd:system/bin/gpsd \
    vendor/samsung/galaxys_sc02b/proprietary/bin/orientationd:system/bin/orientationd \
    vendor/samsung/galaxys_sc02b/proprietary/bin/rild:system/bin/rild \
    vendor/samsung/galaxys_sc02b/proprietary/vendor/firmware/bcm4329.hcd:system/vendor/firmware/bcm4329.hcd \
    vendor/samsung/galaxys_sc02b/proprietary/vendor/firmware/nvram_net.txt:system/vendor/firmware/nvram_net.txt \
    vendor/samsung/galaxys_sc02b/proprietary/vendor/firmware/samsung_mfc_fw.bin:system/vendor/firmware/samsung_mfc_fw.bin
